- src/Middlewares/TreblleMiddleware.php
N/A.
- Bug when response get logged twice on the user's dashboard when response is served using Laravel Octane
N/A.
> 5-two-api-responses-registered-when-using-laravel-octane

- README.md
- config/treblle.php
- src/Middlewares/TreblleMiddleware.php
N/A
N/A
- The  "masked_fields" config key is now a list of values within the config file
- The "TREBLLE_MASKED_FIELDS" env variable is deleted
> 8-provide-complete-control-on-mask-fields

- composer.json
This PR ensures that there is no hard reliance on the Laravel framework.
Instead only some illuminate packages are required.
> [feature] Make sure that this package is not dependant from the framework

- composer.json
- src/TreblleServiceProvider.php
No need to require `illuminate/routing` package
> [feature] No need to require illuminate/routing

- src/Middlewares/TreblleMiddleware.php
- tests/Middlewares/TreblleMiddlewareTest.php
Hi! 
We are testing Treblle in our application. We are using Postmark inbound emails webhooks. The request has a `Cc` key in the request. This can be null, i.e. `[Cc => null]`. The Treblle middleware fails when this is the case: the `maskFields($data)` gets called, the `Cc` field is treated as a masked field, but at line 198 fails because of the `strlen` function. 
/vendor/treblle/treblle-laravel/src/Middlewares/TreblleMiddleware.php in strlen at line 198
`$data[$key] = str_repeat('*', strlen($value));`
This pull request tries to solve that by checking if the masked field in question is null. In that case, we left it as it is (no masking).
Let me know your thoughts on this or if I should do something different. Or simply reject the pull! 
Thanks.
> Request with a null value should be correctly masked

- src/Middlewares/TreblleMiddleware.php
This allows us to extend the middleware. In my case, I need to reduce the amount of data being sent to Treblle.
My plan is to use the `Lottery` class to give some odds as to whether the data is sent or not.
> Don't make `TreblleMiddleware` final

- src/Middlewares/TreblleMiddleware.php
- src/Treblle.php
This enables the project id to be passed when used in route groups - see https://github.com/Treblle/treblle-laravel/issues/61
> Enable the project id to be passed when used in a route group

- src/TreblleServiceProvider.php
pushMiddleware only accepts one argument
Without this change I get error:
```
Illuminate\Contracts\Container\BindingResolutionException: Target class [treblle] does not exist.
```
> Fix call to pushMiddleware

- src/Treblle.php
This handles the scenario that a user for whatever reason does not have a published configuration - this was throwing errors actually into the frontend response.
> handling unpublished configuration

- src/Factories/DataFactory.php
- src/Middlewares/TreblleMiddleware.php
- src/Treblle.php
- src/TreblleServiceProvider.php
This PR removed the manual add to the Laravel HTTP Kernel for the Treblle Middleware, which was causing requests to be sent through twice
> Hot fix/double request bug

- src/Middlewares/TreblleMiddleware.php
We wanted to have as much as low latency we could for Treblle data collection APIs on the SDK level.
This PR uses [pcntl_fork](https://www.php.net/manual/en/function.pcntl-fork.php) extension, which is already part of almost all the PHP installations.
Had look at the alternatives like [AMPHP](https://amphp.org/), [Spatie Fork](https://github.com/spatie/fork) and even looked into Laravel Octane code. alternatives where nice but they had there own requirements. 
Spatie Fork package looked nice though, but we wont be using full package functionalities so didnt make sense to add one more dependency, when we can walk away with simple solution. 
creates a fork of current process, meaning duplicates current process in layman term.
```php
$pid = pcntl_fork();
```
all the below code runs in both …
> feat: Treblle Middleware works with zero latency now

- composer.json
bumps the version of phputils to fix the underlying issue of masking authentication where there is less than 2 entries in the array
> bump of version for phputils

- src/Factories/DataFactory.php
- src/Middlewares/TreblleMiddleware.php
ensures that SymfonyResponse is used as a union type - which should resolve a raised issue from a customer
> ensure symfony response is union type throughout

- src/Treblle.php
I'm playing with Treblle and trying to integrate this library.
It seems some work was recently done on the environment check and the current version has 2 pair of checks that contradict themself:
```
if (! in_array(\config('app.env'), \explode(',', $treblleConfig['ignored_environments']), true)) {
return;
}
```
this will basically reject all environments, except the ones in the ignored_enviroments
the rest of the check will reject all environments in ignored_environments
fixes #88
> removed conflicting check

- src/Middlewares/TreblleMiddleware.php
- tests/Middleware/TreblleMiddlewareTest.php
If a response being sent to Treblle is over 2MB, our infrastructure will reject this as too large. Catching this early in the middleware and warning the user in their logs.
> Testing size of response

- src/Middlewares/TreblleMiddleware.php
This will stop sentry or similar being flooded, and it will just error quietly in the background in production environments
> Only log if the application is not on a production environment

- composer.json
- src/Factories/DataFactory.php
- tests/TestCase.php
This PR updates the `treblle/utils` package, and adds the hostname detection in the data factory. This allows you as a user to recognise which host each request is coming from.
> feature: adding server hostname to server object

- src/Http/Endpoint.php
- src/Middlewares/TreblleMiddleware.php
- tests/Middleware/TreblleMiddlewareTest.php
This PR moves the main logic to the terminate method, for the rare cases that the 'handle' method isn't called but terminate is.
I have also moved the random `Endpoint` selection to a static method on the Enum itself.
This means I have had to remove a test for checking if the header is set for `X-TREBLLE-TRACE-ID` as terminate is a void return.
> fix: moving logic to terminate method

- src/Middlewares/TreblleMiddleware.php
Here is a quickfix for the load time not being calculated as a difference anymore. 
Only problem with this solution is if both `LARAVEL_START` and `REQUEST_TIME_FLOAT` is not set, than we are essentially comparing `microtime(true) - microtime(true)` which would prob. be `0`. 
Not sure if it's an actual issue, but maybe better for that case to return `null` instead or something like that?
> Fix load time not being difference between start and now

- src/Factories/DataFactory.php
Xdebug has a feature to "Break on exception" - generally this is very useful to quickly find exceptions being raised in the application as most of them find their way to the response.
In the changed code, Treblle Laravel integration seems to be using exceptions for control flow - and raises an exception when the response is empty (very common with 204 Status code for example).
This breaks my debugging workflow because I see this exception being raised on every 204 that I return from the app.
To get around this, I rewrote the logic not to raise the exception, but check the error conditions explicitly.
> fix(developer-experience): prevent an annoying exception from being raised when handling empty response
